# Generated by Django 4.1.4 on 2023-01-10 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_d',
            field=models.TextField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='post_t',
            field=models.TextField(default=datetime.datetime.now),
        ),
    ]
